package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DescripcionPastor generated by hbm2java
 */
public class DescripcionPastor  implements java.io.Serializable {


     private String idDescpast;
     private Alumnos alumnos;
     private Empleado empleado;
     private Folder folder;
     private Date fecha;
     private String asunto;
     private String descripcion;

    public DescripcionPastor() {
    }

	
    public DescripcionPastor(String idDescpast) {
        this.idDescpast = idDescpast;
    }
    public DescripcionPastor(String idDescpast, Alumnos alumnos, Empleado empleado, Folder folder, Date fecha, String asunto, String descripcion) {
       this.idDescpast = idDescpast;
       this.alumnos = alumnos;
       this.empleado = empleado;
       this.folder = folder;
       this.fecha = fecha;
       this.asunto = asunto;
       this.descripcion = descripcion;
    }
   
    public String getIdDescpast() {
        return this.idDescpast;
    }
    
    public void setIdDescpast(String idDescpast) {
        this.idDescpast = idDescpast;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Folder getFolder() {
        return this.folder;
    }
    
    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


