package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String idEmpleado;
     private Persona persona;
     private String profesion;
     private String cargo;
     private String area;
     private String foto;
     private Set<DescripcionPastor> descripcionPastors = new HashSet<DescripcionPastor>(0);
     private Set<Sanciones> sancioneses = new HashSet<Sanciones>(0);
     private Set<InformeSeguridad> informeSeguridads = new HashSet<InformeSeguridad>(0);

    public Empleado() {
    }

	
    public Empleado(String idEmpleado, Persona persona) {
        this.idEmpleado = idEmpleado;
        this.persona = persona;
    }
    public Empleado(String idEmpleado, Persona persona, String profesion, String cargo, String area, String foto, Set<DescripcionPastor> descripcionPastors, Set<Sanciones> sancioneses, Set<InformeSeguridad> informeSeguridads) {
       this.idEmpleado = idEmpleado;
       this.persona = persona;
       this.profesion = profesion;
       this.cargo = cargo;
       this.area = area;
       this.foto = foto;
       this.descripcionPastors = descripcionPastors;
       this.sancioneses = sancioneses;
       this.informeSeguridads = informeSeguridads;
    }
   
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set<DescripcionPastor> getDescripcionPastors() {
        return this.descripcionPastors;
    }
    
    public void setDescripcionPastors(Set<DescripcionPastor> descripcionPastors) {
        this.descripcionPastors = descripcionPastors;
    }
    public Set<Sanciones> getSancioneses() {
        return this.sancioneses;
    }
    
    public void setSancioneses(Set<Sanciones> sancioneses) {
        this.sancioneses = sancioneses;
    }
    public Set<InformeSeguridad> getInformeSeguridads() {
        return this.informeSeguridads;
    }
    
    public void setInformeSeguridads(Set<InformeSeguridad> informeSeguridads) {
        this.informeSeguridads = informeSeguridads;
    }




}


