package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Folder generated by hbm2java
 */
public class Folder  implements java.io.Serializable {


     private String idFolder;
     private Alumnos alumnos;
     private String codFolder;
     private String nivel;
     private Character revison;
     private Set<InformeSeguridad> informeSeguridads = new HashSet<InformeSeguridad>(0);
     private Set<Sanciones> sancioneses = new HashSet<Sanciones>(0);
     private Set<PruebasDocumento> pruebasDocumentos = new HashSet<PruebasDocumento>(0);
     private Set<DescripcionPastor> descripcionPastors = new HashSet<DescripcionPastor>(0);
     private Set<InformeBu> informeBus = new HashSet<InformeBu>(0);

    public Folder() {
    }

	
    public Folder(String idFolder) {
        this.idFolder = idFolder;
    }
    public Folder(String idFolder, Alumnos alumnos, String codFolder, String nivel, Character revison, Set<InformeSeguridad> informeSeguridads, Set<Sanciones> sancioneses, Set<PruebasDocumento> pruebasDocumentos, Set<DescripcionPastor> descripcionPastors, Set<InformeBu> informeBus) {
       this.idFolder = idFolder;
       this.alumnos = alumnos;
       this.codFolder = codFolder;
       this.nivel = nivel;
       this.revison = revison;
       this.informeSeguridads = informeSeguridads;
       this.sancioneses = sancioneses;
       this.pruebasDocumentos = pruebasDocumentos;
       this.descripcionPastors = descripcionPastors;
       this.informeBus = informeBus;
    }
   
    public String getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(String idFolder) {
        this.idFolder = idFolder;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public String getCodFolder() {
        return this.codFolder;
    }
    
    public void setCodFolder(String codFolder) {
        this.codFolder = codFolder;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Character getRevison() {
        return this.revison;
    }
    
    public void setRevison(Character revison) {
        this.revison = revison;
    }
    public Set<InformeSeguridad> getInformeSeguridads() {
        return this.informeSeguridads;
    }
    
    public void setInformeSeguridads(Set<InformeSeguridad> informeSeguridads) {
        this.informeSeguridads = informeSeguridads;
    }
    public Set<Sanciones> getSancioneses() {
        return this.sancioneses;
    }
    
    public void setSancioneses(Set<Sanciones> sancioneses) {
        this.sancioneses = sancioneses;
    }
    public Set<PruebasDocumento> getPruebasDocumentos() {
        return this.pruebasDocumentos;
    }
    
    public void setPruebasDocumentos(Set<PruebasDocumento> pruebasDocumentos) {
        this.pruebasDocumentos = pruebasDocumentos;
    }
    public Set<DescripcionPastor> getDescripcionPastors() {
        return this.descripcionPastors;
    }
    
    public void setDescripcionPastors(Set<DescripcionPastor> descripcionPastors) {
        this.descripcionPastors = descripcionPastors;
    }
    public Set<InformeBu> getInformeBus() {
        return this.informeBus;
    }
    
    public void setInformeBus(Set<InformeBu> informeBus) {
        this.informeBus = informeBus;
    }




}


