package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InformeBu generated by hbm2java
 */
public class InformeBu  implements java.io.Serializable {


     private String idInformebu;
     private Alumnos alumnos;
     private Folder folder;
     private String lugar;
     private String descripcion;
     private Date fecha;
     private String gravedad;
     private String motivo;

    public InformeBu() {
    }

	
    public InformeBu(String idInformebu) {
        this.idInformebu = idInformebu;
    }
    public InformeBu(String idInformebu, Alumnos alumnos, Folder folder, String lugar, String descripcion, Date fecha, String gravedad, String motivo) {
       this.idInformebu = idInformebu;
       this.alumnos = alumnos;
       this.folder = folder;
       this.lugar = lugar;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.gravedad = gravedad;
       this.motivo = motivo;
    }
   
    public String getIdInformebu() {
        return this.idInformebu;
    }
    
    public void setIdInformebu(String idInformebu) {
        this.idInformebu = idInformebu;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Folder getFolder() {
        return this.folder;
    }
    
    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getGravedad() {
        return this.gravedad;
    }
    
    public void setGravedad(String gravedad) {
        this.gravedad = gravedad;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


