package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InformeSeguridad generated by hbm2java
 */
public class InformeSeguridad  implements java.io.Serializable {


     private String idInforme;
     private Alumnos alumnos;
     private Empleado empleado;
     private Folder folder;
     private String descInforme;
     private String lugar;
     private Date fecha;
     private Character confirmar;

    public InformeSeguridad() {
    }

	
    public InformeSeguridad(String idInforme, Folder folder) {
        this.idInforme = idInforme;
        this.folder = folder;
    }
    public InformeSeguridad(String idInforme, Alumnos alumnos, Empleado empleado, Folder folder, String descInforme, String lugar, Date fecha, Character confirmar) {
       this.idInforme = idInforme;
       this.alumnos = alumnos;
       this.empleado = empleado;
       this.folder = folder;
       this.descInforme = descInforme;
       this.lugar = lugar;
       this.fecha = fecha;
       this.confirmar = confirmar;
    }
   
    public String getIdInforme() {
        return this.idInforme;
    }
    
    public void setIdInforme(String idInforme) {
        this.idInforme = idInforme;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Folder getFolder() {
        return this.folder;
    }
    
    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    public String getDescInforme() {
        return this.descInforme;
    }
    
    public void setDescInforme(String descInforme) {
        this.descInforme = descInforme;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Character getConfirmar() {
        return this.confirmar;
    }
    
    public void setConfirmar(Character confirmar) {
        this.confirmar = confirmar;
    }




}


