package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1



/**
 * Internos generated by hbm2java
 */
public class Internos  implements java.io.Serializable {


     private String idInterno;
     private Alumnos alumnos;
     private String nropieza;

    public Internos() {
    }

	
    public Internos(String idInterno) {
        this.idInterno = idInterno;
    }
    public Internos(String idInterno, Alumnos alumnos, String nropieza) {
       this.idInterno = idInterno;
       this.alumnos = alumnos;
       this.nropieza = nropieza;
    }
   
    public String getIdInterno() {
        return this.idInterno;
    }
    
    public void setIdInterno(String idInterno) {
        this.idInterno = idInterno;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public String getNropieza() {
        return this.nropieza;
    }
    
    public void setNropieza(String nropieza) {
        this.nropieza = nropieza;
    }




}


