package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
public class Permission  implements java.io.Serializable {


     private String idPermission;
     private Permission permission;
     private String permissionUrl;
     private Character permissionState;
     private String permissionDescription;
     private String permissionTitle;
     private String permissionPosition;
     private String permissionIcono;
     private Set<Permission> permissions = new HashSet<Permission>(0);
     private Set<Rol> rols = new HashSet<Rol>(0);

    public Permission() {
    }

	
    public Permission(String idPermission) {
        this.idPermission = idPermission;
    }
    public Permission(String idPermission, Permission permission, String permissionUrl, Character permissionState, String permissionDescription, String permissionTitle, String permissionPosition, String permissionIcono, Set<Permission> permissions, Set<Rol> rols) {
       this.idPermission = idPermission;
       this.permission = permission;
       this.permissionUrl = permissionUrl;
       this.permissionState = permissionState;
       this.permissionDescription = permissionDescription;
       this.permissionTitle = permissionTitle;
       this.permissionPosition = permissionPosition;
       this.permissionIcono = permissionIcono;
       this.permissions = permissions;
       this.rols = rols;
    }
   
    public String getIdPermission() {
        return this.idPermission;
    }
    
    public void setIdPermission(String idPermission) {
        this.idPermission = idPermission;
    }
    public Permission getPermission() {
        return this.permission;
    }
    
    public void setPermission(Permission permission) {
        this.permission = permission;
    }
    public String getPermissionUrl() {
        return this.permissionUrl;
    }
    
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl;
    }
    public Character getPermissionState() {
        return this.permissionState;
    }
    
    public void setPermissionState(Character permissionState) {
        this.permissionState = permissionState;
    }
    public String getPermissionDescription() {
        return this.permissionDescription;
    }
    
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription;
    }
    public String getPermissionTitle() {
        return this.permissionTitle;
    }
    
    public void setPermissionTitle(String permissionTitle) {
        this.permissionTitle = permissionTitle;
    }
    public String getPermissionPosition() {
        return this.permissionPosition;
    }
    
    public void setPermissionPosition(String permissionPosition) {
        this.permissionPosition = permissionPosition;
    }
    public String getPermissionIcono() {
        return this.permissionIcono;
    }
    
    public void setPermissionIcono(String permissionIcono) {
        this.permissionIcono = permissionIcono;
    }
    public Set<Permission> getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }
    public Set<Rol> getRols() {
        return this.rols;
    }
    
    public void setRols(Set<Rol> rols) {
        this.rols = rols;
    }




}


