package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String idPersona;
     private String nombre;
     private String apellPat;
     private String dni;
     private BigDecimal telefono;
     private String correo;
     private Character state;
     private Character sexo;
     private String apellMat;
     private String username;
     private String password;
     private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Rol> rols = new HashSet<Rol>(0);

    public Persona() {
    }

	
    public Persona(String idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(String idPersona, String nombre, String apellPat, String dni, BigDecimal telefono, String correo, Character state, Character sexo, String apellMat, String username, String password, Set<Alumnos> alumnoses, Set<Empleado> empleados, Set<Rol> rols) {
       this.idPersona = idPersona;
       this.nombre = nombre;
       this.apellPat = apellPat;
       this.dni = dni;
       this.telefono = telefono;
       this.correo = correo;
       this.state = state;
       this.sexo = sexo;
       this.apellMat = apellMat;
       this.username = username;
       this.password = password;
       this.alumnoses = alumnoses;
       this.empleados = empleados;
       this.rols = rols;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellPat() {
        return this.apellPat;
    }
    
    public void setApellPat(String apellPat) {
        this.apellPat = apellPat;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Character getState() {
        return this.state;
    }
    
    public void setState(Character state) {
        this.state = state;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getApellMat() {
        return this.apellMat;
    }
    
    public void setApellMat(String apellMat) {
        this.apellMat = apellMat;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Alumnos> getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set<Alumnos> alumnoses) {
        this.alumnoses = alumnoses;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Rol> getRols() {
        return this.rols;
    }
    
    public void setRols(Set<Rol> rols) {
        this.rols = rols;
    }




}


