package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PruebasDocumento generated by hbm2java
 */
public class PruebasDocumento  implements java.io.Serializable {


     private String idPruebas;
     private String descripcion;
     private String urlPrueba;
     private Set<Folder> folders = new HashSet<Folder>(0);

    public PruebasDocumento() {
    }

	
    public PruebasDocumento(String idPruebas) {
        this.idPruebas = idPruebas;
    }
    public PruebasDocumento(String idPruebas, String descripcion, String urlPrueba, Set<Folder> folders) {
       this.idPruebas = idPruebas;
       this.descripcion = descripcion;
       this.urlPrueba = urlPrueba;
       this.folders = folders;
    }
   
    public String getIdPruebas() {
        return this.idPruebas;
    }
    
    public void setIdPruebas(String idPruebas) {
        this.idPruebas = idPruebas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUrlPrueba() {
        return this.urlPrueba;
    }
    
    public void setUrlPrueba(String urlPrueba) {
        this.urlPrueba = urlPrueba;
    }
    public Set<Folder> getFolders() {
        return this.folders;
    }
    
    public void setFolders(Set<Folder> folders) {
        this.folders = folders;
    }




}


