package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private String idRole;
     private String roleName;
     private Character roleState;
     private String roleDescription;
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Permission> permissions = new HashSet<Permission>(0);

    public Rol() {
    }

	
    public Rol(String idRole) {
        this.idRole = idRole;
    }
    public Rol(String idRole, String roleName, Character roleState, String roleDescription, Set<Persona> personas, Set<Permission> permissions) {
       this.idRole = idRole;
       this.roleName = roleName;
       this.roleState = roleState;
       this.roleDescription = roleDescription;
       this.personas = personas;
       this.permissions = permissions;
    }
   
    public String getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(String idRole) {
        this.idRole = idRole;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Character getRoleState() {
        return this.roleState;
    }
    
    public void setRoleState(Character roleState) {
        this.roleState = roleState;
    }
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<Permission> getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }




}


