package pe.edu.aplication.model;
// Generated 20/04/2016 11:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sanciones generated by hbm2java
 */
public class Sanciones  implements java.io.Serializable {


     private String idSancion;
     private Alumnos alumnos;
     private Empleado empleado;
     private Folder folder;
     private String sancion;
     private Date fechaInicio;
     private Date fechaFinal;
     private String evaluacion;

    public Sanciones() {
    }

	
    public Sanciones(String idSancion) {
        this.idSancion = idSancion;
    }
    public Sanciones(String idSancion, Alumnos alumnos, Empleado empleado, Folder folder, String sancion, Date fechaInicio, Date fechaFinal, String evaluacion) {
       this.idSancion = idSancion;
       this.alumnos = alumnos;
       this.empleado = empleado;
       this.folder = folder;
       this.sancion = sancion;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
       this.evaluacion = evaluacion;
    }
   
    public String getIdSancion() {
        return this.idSancion;
    }
    
    public void setIdSancion(String idSancion) {
        this.idSancion = idSancion;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Folder getFolder() {
        return this.folder;
    }
    
    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    public String getSancion() {
        return this.sancion;
    }
    
    public void setSancion(String sancion) {
        this.sancion = sancion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public String getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(String evaluacion) {
        this.evaluacion = evaluacion;
    }




}


